version: 0.1.0-{build}

branches:
  only:
    - master

image:
  - Visual Studio 2015
  
init:
  - vcpkg install cryptopp
  - vcpkg integrate install

#environment:
#  RECHAIN_HOME:

platform:
  - x64

before_build:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  
build_script:
  - cd build
  - cmake .. -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Test
  - nmake .
  - test\rechain
