version: 0.1.0-{build}

branches:
  only:
    - master

image:
  - Visual Studio 2017
  
init:
  - vcpkg install cryptopp:x64-windows-static
  - vcpkg integrate install

platform:
  - x64

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  
build_script:
  - dir "C:/Tools/vcpkg/packages/cryptopp_x64-windows-static/lib"
  - cd build
  - cmake .. -G "NMake Makefiles" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Test
  - cmake --build .
  - test\rechain
