language: cpp
dist: trusty
sudo: false
compiler: gcc

git:
  lfs_skip_smudge: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcrypto++-dev
      - g++-5

before_install:
      - pip install --user cpp-coveralls

script:
      - source configure.sh
      - make test

after_success:
      - coveralls --exclude data --exclude inc/dependencies --exclude test --gcov-options '\-lp'
