language: cpp

git:
  lfs_skip_smudge: true

matrix:
      include:
            - os: linux
              dist: trusty
              sudo: false
              addons:
                apt:
                  sources:
                    - ubuntu-toolchain-r-test
                  packages:
                    - libboost-all-dev
                    - libcrypto++-dev
                    - g++-5
            - os: osx
              sudo: false

compiler:
      - g++

before_install:
      - if [[ "$OS_NAME" == "osx" ]]; then 
            brew update
            brew install cryptopp; 
            rm '/usr/local/include/c++';
            brew install gcc5;
            eval "$(pyenv init -)";
            pyenv install 3.5.2;
            pyenv rehash
            python3 -m pip install cpp-coveralls;
            pyenv rehash;
        fi
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            pip install --user cpp-coveralls;
        fi

script:
      - if [[ "$OS_NAME" == "osx" ]]; then make test CXX=gcc-5; fi
      - if [[ "$OS_NAME" == "linux" ]]; then make test; fi

after_success:
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
            coveralls --root . --exclude data --exclude inc/dependencies --exclude test --gcov-options '\-lp';
        fi
