language: cpp

git:
  lfs_skip_smudge: true

matrix:
      include:
            - os: linux
              dist: trusty
              sudo: false
              addons:
                apt:
                  sources:
                    - ubuntu-toolchain-r-test
                  packages:
                    - libcrypto++-dev
                    - g++-5
            - os: osx

compiler:
      - g++-5

before_install:
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
            brew install cryptopp; 
            rm '/usr/local/include/c++';
            brew install gcc5;
            brew install pyenv
            eval "$(pyenv init -)"
            pyenv install 3.5.2
            pyenv rehash
            pip install cpp-coveralls
            pyenv rehash
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            pip install --user cpp-coveralls
      - eval "CXX=g++-5"

script:
      - source configure.sh
      - cd build && cmake .. -DCMAKE_BUILD_TYPE=Test && cmake --build .
      - ./test/rechain

after_success:
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls --root .. --exclude data --exclude inc/dependencies -E ".*CMake.*" --exclude test --gcov-options '\-lp'; fi
