language: cpp
dist: trusty
sudo: false
compiler: cmake

git:
  lfs_skip_smudge: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcrypto++-dev

before_install:
      - pip install --user cpp-coveralls

script:
      - source configure.sh
      - ls
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Test
      - make && ./test/rechain

after_success:
      - coveralls --exclude data --exclude inc/dependencies --exclude test --gcov-options '\-lp'
