language: cpp

git:
    lfs_skip_smudge: true
    depth: 99999

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: false
          addons:
              apt:
                  update: true
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - libboost-all-dev
                      - libcrypto++-dev
                      - libtorrent-dev
                      - libtorrent-rasterbar-dev
                      - valgrind
                      - g++-5

before_install:
      - pip install --user cpp-coveralls;

script:
      - make test
      - ./bin/rechain

after_success:
      - coveralls --root . --exclude data --exclude inc/dependencies --exclude test --gcov-options '\-lp';
