language: cpp
dist: trusty
sudo: false
compiler: cmake

git:
  lfs_skip_smudge: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcrypto++-dev
      - g++-5

before_install:
      - pip install --user cpp-coveralls
      - eval "CXX=g++-5"

script:
      - source configure.sh
      - cd build && cmake .. -DCMAKE_BUILD_TYPE=Test
      - make && ./test/rechain

after_success:
      - coveralls --include "build/CMakeFiles/rechain.dir/src/" --gcov-options '\-lp'
