language: cpp

git:
  lfs_skip_smudge: true

matrix:
      include:
            - os: linux
              dist: trusty
              sudo: false
              addons:
                apt:
                  sources:
                    - ubuntu-toolchain-r-test
                  packages:
                    - libboost-all-dev
                    - libcrypto++-dev
                    - libtorrent-dev
                    - libtorrent-rasterbar-dev
                    - g++-5

compiler:
      - g++

before_install:
      - pip install --user cpp-coveralls;

script:
      - make test

after_success:
      - coveralls --root . --exclude data --exclude inc/dependencies --exclude test --gcov-options '\-lp';
