language: cpp
dist: trusty
sudo: false
compiler: gcc
git:
  lfs_skip_smudge: true
addons:
  apt:
    packages:
      - libcrypto++-dev

before_install:
      - pip install --user cpp-coveralls
script:
      - mkdir obj bin
      - make test
after_success:
      - coveralls --exclude inc/dependencies --exclude test --gcov-options '\-lp'
