language: cpp
dist: trusty
sudo: false
compiler: cmake

git:
  lfs_skip_smudge: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcrypto++-dev
      - g++-5

before_install:
      - pip install --user cpp-coveralls
      - eval "CXX=g++-5"

script:
      - source configure.sh
      - cd build && cmake .. -DCMAKE_BUILD_TYPE=Test && cmake --build .
      - ./test/rechain

after_success:
      - coveralls --root .. --exclude data --exclude inc/dependencies -E *CMake* --exclude test --gcov-options '\-lp'
